name: CI

on:
  push:
    branches: [ main, task6 ]
  pull_request:
    branches: [ main, task6 ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: InstallGTest
      run: git clone https://github.com/google/googletest.git -b release-1.11.0 && pwd && ls &&
          mv ${{github.workspace}}/task6/googletest ${{github.workspace}}/task6/3rdparty
      
    - name: Build
      run: mkdir ${{github.workspace}}/task6/build && cd ${{github.workspace}}/task6/build && cmake .. &&
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
